language: csharp
provider: releases
api_key: "hpRuZXxBxJyggobQNGdz"
mono: none
dotnet: 2.0.0
dist: trusty
sudo: false
solution: Nov14_JITA_Training.sln

script:
  - cd Nov14_JITA_Training
  - dotnet restore
  - dotnet build
  - dotnet test FootballApp.test/FootballApp.test.csproj
